### ISSUE TITLE
Github command

### ISSUE THREAD

**Issue by Avamander** [tsahyt/lmrbot#8]
Basically the command should take input in form of ":github [user/org name]/[repository name]". 

The output could look something like this:

> [tsahyt/lmrbot] git.io/repourl - Last commit adbc8d4 was made at Jul 3, 2017 by tsahyt, last issue updated was #8 at Jul 3, 2017 by Avamander. Repository has 0 stars, 2 watching and 2 forks.

git.io link can be generated as described [here](https://github.com/blog/985-git-io-github-url-shortener).

**Comment by tsahyt** [comment]
Done.
